<a href="https://colab.research.google.com/github/TRUONGPHANNGOCTRUC/Machine-Learning/blob/main/Lab_6_20130449_TruongPhanNgocTruc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with classification task using **Random Forests** and **Naïve Bayes** algorithms with/without **Feature Selection**. 

*   **Deadline: 23:59, 25/03/2023**



# Import libraries

In [ ]:
# code
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML'


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/ML


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn import svm
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from prettytable import PrettyTable
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.preprocessing import StandardScaler


#Task 1. 
Task 1. Compare the performance of selected classification algorithms including **Random forest**, **NaiveBayes**, and **SVM** with **mnist** dataset based on **accuracy, precision, recall, f1** measures according to **without using selection feature** and **using selection feature**.



In [ ]:
#mnist
from sklearn import datasets
mnist = datasets.load_digits()
X = mnist.data
y = mnist.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, train_size=0.7,  random_state = 1)

In [ ]:
#Random Forest
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
sicm = confusion_matrix(y_test, y_pred)
rfas = round(accuracy_score(y_test, y_pred),2)
rfps = round(precision_score(y_test,y_pred, average='micro'),2)
rfrs=round(recall_score(y_test, y_pred, average='micro'),2)
rffs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))
     

Confusion Matrix : 
 [[57  0  0  0  1  0  0  0  1  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0  0 49  0  0  0  0  0  0  0]
 [ 0  0  0 61  0  1  0  1  1  0]
 [ 0  0  0  0 61  0  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  1  0]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  1]
 [ 0  0  0  0  0  0  0  0 45  1]
 [ 0  0  0  0  0  2  0  0  0 55]]
Accuracy :  0.9814814814814815
Precision :  0.9814814814814815
Recall :  0.9814814814814815
F1 :  0.9814814814814815


In [ ]:
#NaiveBayes
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
sicm = confusion_matrix(y_test, y_pred)
gaas = round(accuracy_score(y_test, y_pred),2)
gaps = round(precision_score(y_test, y_pred, average='micro'),2)
gars=round(recall_score(y_test, y_pred, average='micro'),2)
gafs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[54  1  0  0  3  0  0  1  0  0]
 [ 0 42  1  0  0  0  0  0  6  0]
 [ 0  5 32  0  0  0  0  0 12  0]
 [ 0  2  2 51  0  1  0  3  5  0]
 [ 1  4  0  0 54  0  0  1  1  0]
 [ 0  2  0  1  0 41  0  2  1  0]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 57  0  0]
 [ 0 10  0  1  0  0  0  1 34  0]
 [ 0  2  0  1  2  3  1  7  8 33]]
Accuracy :  0.8314814814814815
Precision :  0.8314814814814815
Recall :  0.8314814814814815
F1 :  0.8314814814814816


In [ ]:
#SVM
clf = svm.SVC(kernel='rbf')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
rbcm=confusion_matrix(y_test, y_pred)
rbas=round(accuracy_score(y_test, y_pred),2)
rbps=round(precision_score(y_test, y_pred, average='micro'),2)
rbrs=round(recall_score(y_test, y_pred, average='micro'),2)
rbfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[58  0  0  0  1  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  0  0]
 [ 0  0 49  0  0  0  0  0  0  0]
 [ 0  0  1 63  0  0  0  0  0  0]
 [ 0  0  0  0 61  0  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  1]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0  0 56  0  1]
 [ 0  1  0  0  0  0  0  0 44  1]
 [ 0  0  0  0  0  2  0  0  0 55]]
Accuracy :  0.9851851851851852
Precision :  0.9851851851851852
Recall :  0.9851851851851852
F1 :  0.9851851851851852


USING SELECTION FEATURE

In [ ]:
fs = SelectKBest(score_func=f_classif,k=2)
X_selected =  fs.fit_transform(X,y)
Xs_train, Xs_test, ys_train, ys_test = train_test_split(X_selected, y, test_size=0.3, train_size=0.7,  random_state = 1)
clf.fit(Xs_train,ys_train)
ys_pred = clf.predict(Xs_test)

/usr/local/lib/python3.9/dist-packages/sklearn/feature_selection/_univariate_selection.py:112: UserWarning: Features [ 0 32 39] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
/usr/local/lib/python3.9/dist-packages/sklearn/feature_selection/_univariate_selection.py:113: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [ ]:
#Random forest
sicm=confusion_matrix(ys_test, ys_pred)
rfuas=round(accuracy_score(ys_test, ys_pred),2)
rfups=round(precision_score(ys_test, ys_pred, average='micro'),2)
rfurs=round(recall_score(ys_test, ys_pred, average='micro'),2)
rfufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))


Confusion Matrix : 
 [[26  0  0  0  7  1 22  2  0  1]
 [ 2  0 13  0  0  7  6  1 13  7]
 [ 0  0 37  0  0  0  1  0 10  1]
 [ 0  0 48  0  0  1  0  1 13  1]
 [ 9  0  0  0 38  1 10  1  2  0]
 [ 2  0  1  0  1 25  7  0  4  7]
 [ 8  0  0  0  4  9 17  0  6  7]
 [ 2  0 25  0  0  2  4  9 12  3]
 [ 0  0 12  0  0  6  2  2 12 12]
 [ 0  0  7  0  0 13  2  0 20 15]]
Accuracy :  0.3314814814814815
Precision :  0.3314814814814815
Recall :  0.3314814814814815
F1 :  0.3314814814814815


In [ ]:
#Native Bayes
model = GaussianNB()
model.fit(Xs_train, ys_train)
ys_pred = model.predict(Xs_test)
sicm=confusion_matrix(ys_test, ys_pred)
gauas=round(accuracy_score(ys_test, ys_pred),2)
gaups=round(precision_score(ys_test, ys_pred, average='micro'),2)
gaurs=round(recall_score(ys_test, ys_pred, average='micro'),2)
gaufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))


Confusion Matrix : 
 [[22  1  0  0 13 12  7  2  0  2]
 [ 2  0 10  9  1  7  0  1  0 19]
 [ 0  0 11 32  0  1  0  0  0  5]
 [ 0  0  9 48  0  0  0  1  0  6]
 [ 7  1  1  0 43  5  3  1  0  0]
 [ 4  1  2  1  1 14  2  0  0 22]
 [ 7  0  2  0  6 15  8  0  1 12]
 [ 4  0 12 19  1  3  0  7  1 10]
 [ 0  1  6  8  0  2  0  3  1 25]
 [ 0  1  9  5  0  2  0  0  2 38]]
Accuracy :  0.35555555555555557
Precision :  0.35555555555555557
Recall :  0.35555555555555557
F1 :  0.35555555555555557


In [ ]:
#SVM
clf = svm.SVC(kernel='rbf')
#Train the model using the training sets
clf.fit(Xs_train, ys_train)
#Predict the response for test dataset
y_pred = clf.predict(Xs_test)
rbcm=confusion_matrix(ys_test, ys_pred)
rbuas=round(accuracy_score(ys_test, ys_pred),2)
rbups=round(precision_score(ys_test, ys_pred, average='micro'),2)
rburs=round(recall_score(ys_test, ys_pred, average='micro'),2)
rbufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))


Confusion Matrix : 
 [[22  1  0  0 13 12  7  2  0  2]
 [ 2  0 10  9  1  7  0  1  0 19]
 [ 0  0 11 32  0  1  0  0  0  5]
 [ 0  0  9 48  0  0  0  1  0  6]
 [ 7  1  1  0 43  5  3  1  0  0]
 [ 4  1  2  1  1 14  2  0  0 22]
 [ 7  0  2  0  6 15  8  0  1 12]
 [ 4  0 12 19  1  3  0  7  1 10]
 [ 0  1  6  8  0  2  0  3  1 25]
 [ 0  1  9  5  0  2  0  0  2 38]]
Accuracy :  0.35555555555555557
Precision :  0.35555555555555557
Recall :  0.35555555555555557
F1 :  0.35555555555555557


In [ ]:
t= PrettyTable(['Algorithm','Using selection feature', 'Accuracy','Precision','Recall','F1'])
t.add_row(['Random Forest','false',rfas,rfps,rfrs,rffs])
t.add_row(['Random Forest','true',rfuas,rfups,rfurs,rfufs])
t.add_row(['GaussianNB','false',gaas,gaps,gars,gafs])
t.add_row(['GaussianNB','true',gauas,gaups,gaurs,gaufs])
t.add_row(['SVM Radial Basis','false',rbas,rbps,rbrs,rbfs])
t.add_row(['SVM Radial Basis','true',rbuas,rbups,rburs,rbufs])
print(t)

+------------------+-------------------------+----------+-----------+--------+------+
|    Algorithm     | Using selection feature | Accuracy | Precision | Recall |  F1  |
+------------------+-------------------------+----------+-----------+--------+------+
|  Random Forest   |          false          |   0.98   |    0.98   |  0.98  | 0.98 |
|  Random Forest   |           true          |   0.33   |    0.33   |  0.33  | 0.33 |
|    GaussianNB    |          false          |   0.83   |    0.83   |  0.83  | 0.83 |
|    GaussianNB    |           true          |   0.36   |    0.36   |  0.36  | 0.36 |
| SVM Radial Basis |          false          |   0.99   |    0.99   |  0.99  | 0.99 |
| SVM Radial Basis |           true          |   0.36   |    0.36   |  0.36  | 0.36 |
+------------------+-------------------------+----------+-----------+--------+------+


#Task 2. 
For given bank dataset (bank.csv) having the following attributes :
1.	**age** (numeric)
2.	**job** : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3.	**marital** : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4.	**education** (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5.	**default**: has credit in default? (categorical: 'no','yes','unknown')
6.	**housing**: has housing loan? (categorical: 'no','yes','unknown')
7.	**loan**: has personal loan? (categorical: 'no','yes','unknown')
8.	**contact**: contact communication type (categorical: 'cellular','telephone')
9.	**month**: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10.	**day_of_week**: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11.	**duration**: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
12.	**campaign**: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13.	**pdays**: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14.	**previous**: number of contacts performed before this campaign and for this client (numeric)
15.	**poutcome**: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
Output variable (desired target):
16.	**y**. has the client subscribed a term deposit? (binary: 'yes','no')



#3.1. Apply StandardScaler() function to columns that contains numerical data ('age', 'balance', 'day', 'campaign', 'pdays', 'previous')

In [7]:
#code
bank= pd.read_csv('bank.csv')
scaler = StandardScaler()
name=['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
data= bank[name]
bank[['age', 'balance', 'day', 'campaign', 'pdays', 'previous']] = scaler.fit_transform(data[['age', 'balance', 'day', 'campaign', 'pdays', 'previous']])
bank

age          job  marital  education default   balance housing  \
0      1.491505       admin.  married  secondary      no  0.252525     yes   
1      1.239676       admin.  married  secondary      no -0.459974      no   
2     -0.019470   technician  married  secondary      no -0.080160     yes   
3      1.155733     services  married  secondary      no  0.293762     yes   
4      1.071790       admin.  married   tertiary      no -0.416876      no   
...         ...          ...      ...        ...     ...       ...     ...   
11157 -0.691015  blue-collar   single    primary      no -0.473616     yes   
11158 -0.187357     services  married  secondary      no -0.246658      no   
11159 -0.774958   technician   single  secondary      no -0.464934      no   
11160  0.148416   technician  married  secondary      no -0.473926      no   
11161 -0.607072   technician  married  secondary      no -0.473926      no   

      loan   contact       day month  duration  campaign     pdays  previous  \
0       no   unknown -1.265746   may      1042 -0.554168 -0.481184 -0.363260   
1       no   unknown -1.265746   may      1467 -0.554168 -0.481184 -0.363260   
2       no   unknown -1.265746   may      1389 -0.554168 -0.481184 -0.363260   
3       no   unknown -1.265746   may       579 -0.554168 -0.481184 -0.363260   
4       no   unknown -1.265746   may       673 -0.186785 -0.481184 -0.363260   
...    ...       ...       ...   ...       ...       ...       ...       ...   
11157   no  cellular  0.515650   apr       257 -0.554168 -0.481184 -0.363260   
11158   no   unknown  0.040612   jun        83  0.547981 -0.481184 -0.363260   
11159   no  cellular  0.396891   aug       156 -0.186785 -0.481184 -0.363260   
11160  yes  cellular -0.909466   may         9 -0.186785  1.109571  1.818332   
11161   no  cellular -0.790707   jul       628 -0.554168 -0.481184 -0.363260   

      poutcome deposit  
0      unknown     yes  
1      unknown     yes  
2      unknown     yes  
3      unknown     yes  
4      unknown     yes  
...        ...     ...  
11157  unknown      no  
11158  unknown      no  
11159  unknown      no  
11160  failure      no  
11161  unknown      no  

[11162 rows x 17 columns]

#3.2. Apply Encode Categorical Value (OneHotEncoder) to transfrom categorical data to numerical data ('job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome')

In [8]:
#code
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
bank = pd.get_dummies(bank,drop_first=True)
bank


age   balance       day  duration  campaign     pdays  previous  \
0      1.491505  0.252525 -1.265746      1042 -0.554168 -0.481184 -0.363260   
1      1.239676 -0.459974 -1.265746      1467 -0.554168 -0.481184 -0.363260   
2     -0.019470 -0.080160 -1.265746      1389 -0.554168 -0.481184 -0.363260   
3      1.155733  0.293762 -1.265746       579 -0.554168 -0.481184 -0.363260   
4      1.071790 -0.416876 -1.265746       673 -0.186785 -0.481184 -0.363260   
...         ...       ...       ...       ...       ...       ...       ...   
11157 -0.691015 -0.473616  0.515650       257 -0.554168 -0.481184 -0.363260   
11158 -0.187357 -0.246658  0.040612        83  0.547981 -0.481184 -0.363260   
11159 -0.774958 -0.464934  0.396891       156 -0.186785 -0.481184 -0.363260   
11160  0.148416 -0.473926 -0.909466         9 -0.186785  1.109571  1.818332   
11161 -0.607072 -0.473926 -0.790707       628 -0.554168 -0.481184 -0.363260   

       job_blue-collar  job_entrepreneur  job_housemaid  ...  month_jun  \
0                    0                 0              0  ...          0   
1                    0                 0              0  ...          0   
2                    0                 0              0  ...          0   
3                    0                 0              0  ...          0   
4                    0                 0              0  ...          0   
...                ...               ...            ...  ...        ...   
11157                1                 0              0  ...          0   
11158                0                 0              0  ...          1   
11159                0                 0              0  ...          0   
11160                0                 0              0  ...          0   
11161                0                 0              0  ...          0   

       month_mar  month_may  month_nov  month_oct  month_sep  poutcome_other  \
0              0          1          0          0          0               0   
1              0          1          0          0          0               0   
2              0          1          0          0          0               0   
3              0          1          0          0          0               0   
4              0          1          0          0          0               0   
...          ...        ...        ...        ...        ...             ...   
11157          0          0          0          0          0               0   
11158          0          0          0          0          0               0   
11159          0          0          0          0          0               0   
11160          0          1          0          0          0               0   
11161          0          0          0          0          0               0   

       poutcome_success  poutcome_unknown  deposit_yes  
0                     0                 1            1  
1                     0                 1            1  
2                     0                 1            1  
3                     0                 1            1  
4                     0                 1            1  
...                 ...               ...          ...  
11157                 0                 1            0  
11158                 0                 1            0  
11159                 0                 1            0  
11160                 0                 0            0  
11161                 0                 1            0  

[11162 rows x 43 columns]

#3.3. Apply **Decision tree, Random forest, kNN, NaïveBayes** to preproceed dataset in the previous steps. Then compare the obtained results using **accuracy, precision, recall, f1** measures.

In [9]:
#random forest
clf=RandomForestClassifier(n_estimators=100)
X= bank.iloc[:,:-1]
# X
Y= bank.iloc[:, -1]
# Y
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
sicm=confusion_matrix(y_test, y_pred)
rfas=round(accuracy_score(y_test, y_pred),2)
rfps=round(precision_score(y_test, y_pred, average='micro'),2)
rfrs=round(recall_score(y_test, y_pred, average='micro'),2)
rffs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))


Confusion Matrix : 
 [[1460  300]
 [ 194 1395]]
Accuracy :  0.85249328157659
Precision :  0.85249328157659
Recall :  0.85249328157659
F1 :  0.85249328157659


In [10]:
#NativeBayes
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
sicm=confusion_matrix(y_test, y_pred)
gaas=round(accuracy_score(y_test, y_pred),2)
gaps=round(precision_score(y_test, y_pred, average='micro'),2)
gars=round(recall_score(y_test, y_pred, average='micro'),2)
gafs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))


Confusion Matrix : 
 [[1545  215]
 [ 738  851]]
Accuracy :  0.7154374440131382
Precision :  0.7154374440131382
Recall :  0.7154374440131382
F1 :  0.7154374440131384


In [11]:
#SVM
clf = svm.SVC(kernel='rbf')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
rbcm=confusion_matrix(y_test, y_pred)
rbas=round(accuracy_score(y_test, y_pred),2)
rbps=round(precision_score(y_test, y_pred, average='micro'),2)
rbrs=round(recall_score(y_test, y_pred, average='micro'),2)
rbfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))


Confusion Matrix : 
 [[1380  380]
 [ 548 1041]]
Accuracy :  0.7229023589131084
Precision :  0.7229023589131084
Recall :  0.7229023589131084
F1 :  0.7229023589131084


In [12]:
t= PrettyTable(['Liner Kernel', 'Accuracy','Precision','Recall','F1'])
t.add_row(['SVM Radial Basis',rbas,rbps,rbrs,rbfs])
t.add_row(['GaussianNB',gaas,gaps,gars,gafs])
t.add_row(['Random forest',rfas,rfps,rfrs,rffs])
print(t)

+------------------+----------+-----------+--------+------+
|   Liner Kernel   | Accuracy | Precision | Recall |  F1  |
+------------------+----------+-----------+--------+------+
| SVM Radial Basis |   0.72   |    0.72   |  0.72  | 0.72 |
|    GaussianNB    |   0.72   |    0.72   |  0.72  | 0.72 |
|  Random forest   |   0.85   |    0.85   |  0.85  | 0.85 |
+------------------+----------+-----------+--------+------+


#3.4. Using selection feature to above dataset, then compare the classification results with those in Task 2.3. 

In [13]:
#code
fs = SelectKBest(score_func=f_classif, k=2)
# apply feature selection
X_selected = fs.fit_transform(X, Y)
Xs_train, Xs_test, ys_train, ys_test = train_test_split(X_selected, Y, test_size=0.3, train_size=0.7,  random_state = 1)
clf.fit(Xs_train,ys_train)
ys_pred = clf.predict(Xs_test)

In [14]:
#randomforest
sicm=confusion_matrix(ys_test, ys_pred)
rfuas=round(accuracy_score(ys_test, ys_pred),2)
rfups=round(precision_score(ys_test, ys_pred, average='micro'),2)
rfurs=round(recall_score(ys_test, ys_pred, average='micro'),2)
rfufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))

Confusion Matrix : 
 [[1373  387]
 [ 546 1043]]
Accuracy :  0.7214093759331144
Precision :  0.7214093759331144
Recall :  0.7214093759331144
F1 :  0.7214093759331144


In [15]:
#NativeBayes
model = GaussianNB()
model.fit(Xs_train, ys_train)
ys_pred = model.predict(Xs_test)
sicm=confusion_matrix(ys_test, ys_pred)
gauas=round(accuracy_score(ys_test, ys_pred),2)
gaups=round(precision_score(ys_test, ys_pred, average='micro'),2)
gaurs=round(recall_score(ys_test, ys_pred, average='micro'),2)
gaufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))

Confusion Matrix : 
 [[1657  103]
 [ 818  771]]
Accuracy :  0.7249925350851
Precision :  0.7249925350851
Recall :  0.7249925350851
F1 :  0.7249925350851001


In [16]:
#SVM
clf = svm.SVC(kernel='rbf')
#Train the model using the training sets
clf.fit(Xs_train, ys_train)
#Predict the response for test dataset
y_pred = clf.predict(Xs_test)
rbcm=confusion_matrix(ys_test, ys_pred)
rbuas=round(accuracy_score(ys_test, ys_pred),2)
rbups=round(precision_score(ys_test, ys_pred, average='micro'),2)
rburs=round(recall_score(ys_test, ys_pred, average='micro'),2)
rbufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))

Confusion Matrix : 
 [[1657  103]
 [ 818  771]]
Accuracy :  0.7249925350851
Precision :  0.7249925350851
Recall :  0.7249925350851
F1 :  0.7249925350851001


In [17]:
t= PrettyTable(['Algorithm','Using selection feature', 'Accuracy','Precision','Recall','F1'])
t.add_row(['Random Forest','false',rfas,rfps,rfrs,rffs])
t.add_row(['Random Forest','true',rfuas,rfups,rfurs,rfufs])
t.add_row(['GaussianNB','false',gaas,gaps,gars,gafs])
t.add_row(['GaussianNB','true',gauas,gaups,gaurs,gaufs])
t.add_row(['SVM Radial Basis','false',rbas,rbps,rbrs,rbfs])
t.add_row(['SVM Radial Basis','true',rbuas,rbups,rburs,rbufs])
print(t)

+------------------+-------------------------+----------+-----------+--------+------+
|    Algorithm     | Using selection feature | Accuracy | Precision | Recall |  F1  |
+------------------+-------------------------+----------+-----------+--------+------+
|  Random Forest   |          false          |   0.85   |    0.85   |  0.85  | 0.85 |
|  Random Forest   |           true          |   0.72   |    0.72   |  0.72  | 0.72 |
|    GaussianNB    |          false          |   0.72   |    0.72   |  0.72  | 0.72 |
|    GaussianNB    |           true          |   0.72   |    0.72   |  0.72  | 0.72 |
| SVM Radial Basis |          false          |   0.72   |    0.72   |  0.72  | 0.72 |
| SVM Radial Basis |           true          |   0.72   |    0.72   |  0.72  | 0.72 |
+------------------+-------------------------+----------+-----------+--------+------+


#Task 4. 
For a given dataset in the Lab #5 (**credit card dataset**), perform feature selection and thencompare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression, SVM, Random Forest and NaiveBayes) based on accuracy, precision, recall, f1 measures.


In [18]:
# code
creditcard= pd.read_csv('creditcard.csv')
creditcard

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [19]:
#randomForest
clf=RandomForestClassifier(n_estimators=100)
X= data.iloc[1:50000, 1:-1]
Y= data.iloc[1:50000, -1]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
sicm=confusion_matrix(y_test, y_pred)
rfas=round(accuracy_score(y_test, y_pred),2)
rfps=round(precision_score(y_test, y_pred, average='micro'),2)
rfrs=round(recall_score(y_test, y_pred, average='micro'),2)
rffs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))


Confusion Matrix : 
 [[2491    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0]
 [   0  132   87   27   11    5    8    1    2    0    0    0    0    0
     1    0    1    0    0    0    0    0    0    0    1    0]
 [   0   98   56   22    9    3    3    0    4    0    0    1    0    0
     0    0    0    1    0    0    0    0    1    0    0    0]
 [   0   68   36   14    9    7    3    0    2    0    0    0    0    0
     0    0    1    0    1    0    0    0    0    0    0    0]
 [   0   28   22   11    5    2    1    0    1    0    0    1    1    0
     0    0    0    0    0    0    0    0    0    0    0    0]
 [   0   17   14    3    6    1    2    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    9   10    6    1    3    0    1    0    1    0    0    0    1
     0    0    0    0    0    0    0    0    0    0    0    0]
 [   0   10   11    4    0    2   

In [20]:
#NativeBayes
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
sicm=confusion_matrix(y_test, y_pred)
gaas=round(accuracy_score(y_test, y_pred),2)
gaps=round(precision_score(y_test, y_pred, average='micro'),2)
gars=round(recall_score(y_test, y_pred, average='micro'),2)
gafs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Confusion Matrix : 
 [[2481    0    0   10    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   0  204   53   11    3    0    3    0    0    0    0    0    0    0
     0    0    1    0    0    0    0    1    0    0    0]
 [   0  145   39    8    1    0    4    0    0    0    0    0    0    0
     0    0    1    0    0    0    0    0    0    0    0]
 [   0   92   45    1    2    0    1    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   0   43   23    2    1    0    2    0    0    0    0    0    0    0
     0    0    1    0    0    0    0    0    0    0    0]
 [   0   21   15    2    2    0    3    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   0   18    8    3    0    0    3    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0]
 [   0    9   12    3    3    0    0    0    0    0    0    0    0   

In [21]:
#SVM
clf = svm.SVC(kernel='rbf')
#Train the model using the training sets
clf.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = clf.predict(X_test)
rbcm=confusion_matrix(y_test, y_pred)
rbas=round(accuracy_score(y_test, y_pred),2)
rbps=round(precision_score(y_test, y_pred, average='micro'),2)
rbrs=round(recall_score(y_test, y_pred, average='micro'),2)
rbfs=round(f1_score(y_test, y_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(y_test, y_pred))
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred, average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))


Confusion Matrix : 
 [[2491    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [ 101  175    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [  79  118    0    1    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [  65   76    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [  29   43    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [  21   22    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [  17   15    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [  14   13    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   9    6    0   

USNG SELECTION FEATURE

In [22]:
fs = SelectKBest(score_func=f_classif, k=2)
# apply feature selection
X_selected = fs.fit_transform(X, Y)
Xs_train, Xs_test, ys_train, ys_test = train_test_split(X_selected, Y, test_size=0.3, train_size=0.7,  random_state = 1)
clf.fit(Xs_train,ys_train)
ys_pred = clf.predict(Xs_test)

In [23]:
#RandomForest
sicm=confusion_matrix(ys_test, ys_pred)
rfuas=round(accuracy_score(ys_test, ys_pred),2)
rfups=round(precision_score(ys_test, ys_pred, average='micro'),2)
rfurs=round(recall_score(ys_test, ys_pred, average='micro'),2)
rfufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))


Confusion Matrix : 
 [[2491    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   2  269    5    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   0  196    2    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   5  136    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   0   71    1    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   1   42    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   3   28    1    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   1   26    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0]
 [   1   14    0   

In [24]:
#NativeBayes
model = GaussianNB()
model.fit(Xs_train, ys_train)
ys_pred = model.predict(Xs_test)
sicm=confusion_matrix(ys_test, ys_pred)
gauas=round(accuracy_score(ys_test, ys_pred),2)
gaups=round(precision_score(ys_test, ys_pred, average='micro'),2)
gaurs=round(recall_score(ys_test, ys_pred, average='micro'),2)
gaufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))

Confusion Matrix : 
 [[2491    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0  250   17    0    5    0    3    0    0    0    0    0    0    0
     0    0    0    0    1    0    0    0    0    0    0    0    0]
 [   0  182    8    0    3    0    3    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    1    1    0    0]
 [   0  123   15    0    1    0    2    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0   60    8    0    2    0    2    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0   32    6    0    2    0    2    0    0    0    0    0    0    0
     0    0    1    0    0    0    0    0    0    0    0    0    0]
 [   0   27    2    0    0    0    3    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0]

In [25]:
#SVM
model = GaussianNB()
model.fit(Xs_train, ys_train)
ys_pred = model.predict(Xs_test)
sicm=confusion_matrix(ys_test, ys_pred)
gauas=round(accuracy_score(ys_test, ys_pred),2)
gaups=round(precision_score(ys_test, ys_pred, average='micro'),2)
gaurs=round(recall_score(ys_test, ys_pred, average='micro'),2)
gaufs=round(f1_score(ys_test, ys_pred, average='micro'),2)
print ("Confusion Matrix : \n", confusion_matrix(ys_test, ys_pred))
print ("Accuracy : ", accuracy_score(ys_test, ys_pred))
print ("Precision : ", precision_score(ys_test, ys_pred, average='micro'))
print ("Recall : ", recall_score(ys_test, ys_pred, average='micro'))
print ("F1 : ", f1_score(ys_test, ys_pred, average='micro'))

Confusion Matrix : 
 [[2491    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0  250   17    0    5    0    3    0    0    0    0    0    0    0
     0    0    0    0    1    0    0    0    0    0    0    0    0]
 [   0  182    8    0    3    0    3    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    1    1    0    0]
 [   0  123   15    0    1    0    2    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0   60    8    0    2    0    2    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0   32    6    0    2    0    2    0    0    0    0    0    0    0
     0    0    1    0    0    0    0    0    0    0    0    0    0]
 [   0   27    2    0    0    0    3    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0]

In [26]:
t= PrettyTable(['Algorithm','Using selection feature', 'Accuracy','Precision','Recall','F1'])
t.add_row(['Random Forest','false',rfas,rfps,rfrs,rffs])
t.add_row(['Random Forest','true',rfuas,rfups,rfurs,rfufs])
t.add_row(['GaussianNB','false',gaas,gaps,gars,gafs])
t.add_row(['GaussianNB','true',gauas,gaups,gaurs,gaufs])
t.add_row(['SVM Radial Basis','false',rbas,rbps,rbrs,rbfs])
t.add_row(['SVM Radial Basis','true',rbuas,rbups,rburs,rbufs])
print(t)

+------------------+-------------------------+----------+-----------+--------+------+
|    Algorithm     | Using selection feature | Accuracy | Precision | Recall |  F1  |
+------------------+-------------------------+----------+-----------+--------+------+
|  Random Forest   |          false          |   0.81   |    0.81   |  0.81  | 0.81 |
|  Random Forest   |           true          |   0.82   |    0.82   |  0.82  | 0.82 |
|    GaussianNB    |          false          |   0.81   |    0.81   |  0.81  | 0.81 |
|    GaussianNB    |           true          |   0.82   |    0.82   |  0.82  | 0.82 |
| SVM Radial Basis |          false          |   0.8    |    0.8    |  0.8   | 0.8  |
| SVM Radial Basis |           true          |   0.72   |    0.72   |  0.72  | 0.72 |
+------------------+-------------------------+----------+-----------+--------+------+


#Finally,
Save a copy in your Github. Remember renaming the notebook.